# Generated by Django 5.2.7 on 2025-11-03 10:00

from django.db import migrations
from django.utils.text import slugify

# 我们将要添加的分类
CATEGORIES = [
    "Python 开发",
    "Web 前端",
    "数据科学",
    "人工智能",
    "移动开发",
    "云计算 / DevOps",
    "软件测试",
]

def populate_categories(apps, schema_editor):
    """
    循环 CATEGORIES 列表, 创建 Category 对象
    """
    Category = apps.get_model('core', 'Category')
    for name in CATEGORIES:
        # get_or_create 会检查是否存在, 避免重复创建
        Category.objects.get_or_create(
            name=name,
            # 【【【修复】】】: 告诉 slugify 允许中文
            defaults={'slug': slugify(name, allow_unicode=True)}
        )

def remove_categories(apps, schema_editor):
    """
    (可选) 定义如何“撤销”这个迁移
    """
    Category = apps.get_model('core', 'Category')
    Category.objects.filter(name__in=CATEGORIES).delete()


class Migration(migrations.Migration):

    # 它依赖于我们刚刚创建的 0001_initial
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # 运行 populate_categories 函数
        migrations.RunPython(populate_categories, remove_categories),
    ]