# Generated by Django 5.2.7 on 2025-11-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_mp4_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos_mp4/', verbose_name='上传的MP4原文件'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', '视频'), ('text', '文本')], default='text', max_length=10, verbose_name='课时类型'),
        ),
    ]
