# Generated by Django 5.0.3 on 2025-11-05 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.lesson', verbose_name='所属课时')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
