# Generated by Django 5.0.3 on 2025-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorited_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.course', verbose_name='收藏的课程'),
        ),
    ]
