# Generated by Django
# 这是自动生成的迁移文件，用于从 Course 模型中移除 price 字段

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # 依赖于你最新的迁移文件
        ('core', '0004_customuser_favorited_courses'),
    ]

    operations = [
        # 核心操作：移除字段
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]