# Generated by Django 5.2.7 on 2025-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_course_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favorited_courses',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='课程标题'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', '视频'), ('text', '文本')], db_index=True, default='text', max_length=10, verbose_name='课时类型'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='课时顺序'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='章节顺序'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['lesson', '-created_at'], name='core_commen_lesson__e3bbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='core_commen_user_id_315d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='core_course_created_4df6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', '-created_at'], name='core_course_categor_368768_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', '-created_at'], name='core_course_instruc_269304_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', '-enrolled_at'], name='core_enroll_student_8919b2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', '-enrolled_at'], name='core_enroll_course__43599a_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='core_lesson_module__bc71c5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='core_lesson_lesson__f15437_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['student', 'is_completed'], name='core_lesson_student_5613ea_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'is_completed'], name='core_lesson_lesson__e27728_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='core_module_course__d6848a_idx'),
        ),
    ]
