# Generated by Django 5.0.3 on 2025-11-14 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_options_remove_course_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorited_courses',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='core.course', verbose_name='收藏的课程'),
        ),
    ]
