# Generated by Django 5.2.7 on 2025-11-14 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_likes_customuser_favorited_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='core_commen_lesson__e3bbc9_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='core_commen_user_id_315d2e_idx',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_received', to=settings.AUTH_USER_MODEL, verbose_name='回复对象'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['lesson', 'created_at'], name='core_commen_lesson__a19e30_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='core_commen_user_id_65cc57_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='core_commen_parent__cc187b_idx'),
        ),
    ]
