# Generated by Django 5.2.7 on 2025-11-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='观看次数'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-view_count'], name='core_course_view_co_027f5a_idx'),
        ),
    ]
