# Generated by Django 5.2.8 on 2025-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, help_text='支持上传代码、文档、图片、压缩包等', null=True, upload_to='assignments/', verbose_name='作业附件'),
        ),
    ]
