# Generated by Django 5.2.8 on 2025-12-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assignment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attachment',
            field=models.FileField(blank=True, help_text='学生提交的作业文件', null=True, upload_to='submissions/', verbose_name='提交附件'),
        ),
    ]
