# Generated by Django 5.2.8 on 2025-12-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_submission_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer_key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='正确答案'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('regular', '图文/文件作业'), ('choice', '选择题')], default='regular', max_length=20, verbose_name='作业类型'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='choices_data',
            field=models.TextField(blank=True, null=True, verbose_name='选项数据(JSON)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='作业要求(或题目描述)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(verbose_name='作业内容(代码/链接/选项)'),
        ),
    ]
