# Generated by Django 5.2.8 on 2025-12-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignment_answer_key_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='answer_key',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='choices_data',
        ),
        migrations.AddField(
            model_name='assignment',
            name='quiz_data',
            field=models.TextField(blank=True, null=True, verbose_name='题目数据(JSON)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('regular', '图文/文件作业'), ('choice', '选择题(多题)')], default='regular', max_length=20, verbose_name='作业类型'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='作业附件'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='提交附件'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(verbose_name='作业内容'),
        ),
    ]
